### ISSUE TITLE
Application crashes on launch due to BeaconService declaration in manifest

### ISSUE THREAD

**Issue by flame-0** [mjaakko/NeoStumbler#157]
Running [1.2.3: full](https://github.com/mjaakko/NeoStumbler/releases/tag/1.2.3) on Android 14 QPR3 / LineageOS 21
```
FATAL EXCEPTION: main
Process: xyz.malkki.neostumbler, PID: 21607
java.lang.RuntimeException: Unable to create application xyz.malkki.neostumbler.StumblerApplication: org.altbeacon.beacon.BeaconManager$ServiceNotDeclaredException: The BeaconService is not properly declared in AndroidManifest.xml.  If using Eclipse, please verify that your project.properties has manifestmerger.enabled=true
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7403)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: org.altbeacon.beacon.BeaconManager$ServiceNotDeclaredException: The BeaconService is not properly declared in AndroidManifest.xml.  If using Eclipse, please verify that your project.properties has manifestmerger.enabled=true
	at org.altbeacon.beacon.BeaconManager.verifyServiceDeclaration(Unknown Source:32)
	at org.altbeacon.beacon.BeaconManager.<init>(Unknown Source:127)
	at org.altbeacon.beacon.BeaconManager.getInstanceForApplication(Unknown Source:13)
	at xyz.malkki.neostumbler.StumblerApplication.onCreate(Unknown Source:8)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1392)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7398)
	... 9 more
```

**Comment by mjaakko** [comment]
Hmm, interesting. Could you try whether this happens also with the fdroid variant?

**Comment by mjaakko** [comment]
Looks like this can be fixed by disabling manifest checking done by the BeaconLibrary: https://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/BeaconManager.html#setManifestCheckingDisabled(boolean)

Maybe LineageOS has something that causes the application to not see the manifest correctly

**Comment by flame-0** [comment]
> Hmm, interesting. Could you try whether this happens also with the fdroid variant?

I can open and use the F-Droid variant. I have been using the 1.2.3-full version since its release, but I just got that error today, weird.

**Comment by flame-0** [comment]
@mjaakko, I was able to start the application again. It was the [App Manager](https://github.com/MuntashirAkon/AppManager)'s feature to block trackers that caused the issue. Sorry for the inconvenience.

![Screenshot_20240724-004735_App Manager](https://github.com/user-attachments/assets/d9a6e71d-06d7-4767-88e0-a251df55692d)
