### ISSUE TITLE
The application crashes, hangs, or freezes.

### ISSUE THREAD

**Issue by DocSniper** [mjaakko/NeoStumbler#272]
### Description

The application crashes, hangs, or freezes sometimes when starting the app, and sometimes when initiating a scan.

### App variant

fdroid

### Version

1.3.2

### Device

Shiba

### Android version

Android 14 - LineageOS 21

### Logs

```shell
10-09 09:29:06.794 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:06.814 I/AppLocaleUtil(25350): Can display preference - [xyz.malkki.neostumbler.fdroid] : isDisallowedPackage : false / isSignedWithPlatformKey : false / hasLauncherEntry : true / canDisplay : true / 1.1
10-09 09:29:07.086 D/HotseatPredictionController(17543): } targetComponent=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=NeoStumbler), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd
10-09 09:29:07.369 I/ActivityTaskManager( 1497): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=xyz.malkki.neostumbler.fdroid cmp=xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} with LAUNCH_MULTIPLE from uid 1000 (BAL_ALLOW_ALLOWLISTED_UID) result code=0
10-09 09:29:07.371 V/WindowManagerShell( 2306): Transition requested (#2836): android.os.BinderProxy@f3fb13d TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=3025 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=xyz.malkki.neostumbler.fdroid cmp=xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity } baseActivity=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} topActivity=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} origActivity=null realActivity=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} numActivities=1 lastActiveTime=234024768 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@84d3d32} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 132 - 0, 0) topActivityInfo=ActivityInfo{8347a83 xyz.malkki.neostumbler.MainActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1080 topActivityLetterboxHeight=2400 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 2836 }
10-09 09:29:07.387 D/CoreBackPreview( 1497): Window{f0145d6 u0 Splash Screen xyz.malkki.neostumbler.fdroid}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@bb1b02d, mPriority=0, mIsAnimationCallback=false}
10-09 09:29:07.389 I/ActivityManager( 1497): Start proc 11201:xyz.malkki.neostumbler.fdroid/u0a391 for next-top-activity {xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity}
10-09 09:29:07.408 V/WindowManager( 1497): Sent Transition (#2836) createdAt=10-09 09:29:07.366 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=3025 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=xyz.malkki.neostumbler.fdroid cmp=xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity } baseActivity=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} topActivity=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} origActivity=null realActivity=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} numActivities=1 lastActiveTime=234024768 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{d956adc Task{ba194fe #3025 type=standard A=10391:xyz.malkki.neostumbler.fdroid}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 132 - 0, 0) topActivityInfo=ActivityInfo{68a98b9 xyz.malkki.neostumbler.MainActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1080 topActivityLetterboxHeight=2400 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 2836 }
10-09 09:29:07.408 V/WindowManager( 1497):         {WCT{RemoteToken{d956adc Task{ba194fe #3025 type=standard A=10391:xyz.malkki.neostumbler.fdroid}}} m=OPEN f=NONE leash=Surface(name=Task=3025)/@0xbdb39ae sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},
10-09 09:29:07.434 D/nativeloader(11201): Configuring clns-6 for other apk /data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/lib/arm64:/data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/xyz.malkki.neostumbler.fdroid
10-09 09:29:07.439 V/GraphicsEnvironment(11201): xyz.malkki.neostumbler.fdroid is not listed in per-application setting
10-09 09:29:07.444 I/BeaconManager(11201): BeaconManager started up on pid 11201 named 'xyz.malkki.neostumbler.fdroid' for application package 'xyz.malkki.neostumbler.fdroid'.  isMainProcess=true
10-09 09:29:07.448 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:07.448 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:07.448 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:07.453 D/vulkan  (11201): searching for layers in '/data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/lib/arm64'
10-09 09:29:07.453 D/vulkan  (11201): searching for layers in '/data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/base.apk!/lib/arm64-v8a'
10-09 09:29:07.489 D/CoreBackPreview( 1497): Window{cfcf0d1 u0 xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@7f6da10, mPriority=0, mIsAnimationCallback=false}
10-09 09:29:07.550 I/ActivityTaskManager( 1497): Displayed xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity for user 0: +179ms
10-09 09:29:07.580 I/ImeTracker( 1497): xyz.malkki.neostumbler.fdroid:25912f54: onRequestHide at ORIGIN_SERVER reason HIDE_UNSPECIFIED_WINDOW fromUser false
10-09 09:29:07.580 I/ImeTracker( 1497): xyz.malkki.neostumbler.fdroid:25912f54: onCancelled at PHASE_SERVER_SHOULD_HIDE
10-09 09:29:07.822 D/CoreBackPreview( 1497): Window{f0145d6 u0 Splash Screen xyz.malkki.neostumbler.fdroid EXITING}: Setting back callback null
10-09 09:29:07.823 W/InputManager-JNI( 1497): Input channel object 'f0145d6 Splash Screen xyz.malkki.neostumbler.fdroid (client)' was disposed without first being removed with the input manager!
10-09 09:29:09.109 W/ndroid.settings(25350): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/base.apk' with 1 weak references
10-09 09:29:10.222 V/com.jarsilio.android.waveup (WaveUpWorldState)(20613): Most recently run package according to UsageStats (>= LOLLIPOP): xyz.malkki.neostumbler.fdroid
10-09 09:29:10.224 V/com.jarsilio.android.waveup (WaveUpWorldState)(20613): Most recently run package according to UsageStats (>= LOLLIPOP): xyz.malkki.neostumbler.fdroid
10-09 09:29:11.135 I/ActivityManager( 1497): Background started FGS: Allowed [callingPackage: xyz.malkki.neostumbler.fdroid; callingUid: 10391; uidState: TOP ; uidBFSL: [BFSL]; intent: Intent { cmp=xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.scanner.ScannerService (has extras) }; code:PROC_STATE_TOP; tempAllowListReason:<,reasonCode:SYSTEM_ALLOW_LISTED,duration:9223372036854775807,callingUid:-1>; targetSdkVersion:34; callerTargetSdkVersion:34; startForegroundCount:0; bindFromPackage:null: isBindService:false]
10-09 09:29:11.142 D/TileServices( 2306): Couldn't find tile for ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.scanner.quicksettings.ScannerTileService}(0)
10-09 09:29:11.148 I/WifiService( 1497): acquireWifiLock uid=10391 lockMode=4 packageName=xyz.malkki.neostumbler.fdroid
10-09 09:29:11.202 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:11.203 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:11.204 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:11.208 I/ActivityManager( 1497): Background started FGS: Allowed [callingPackage: xyz.malkki.neostumbler.fdroid; callingUid: 10391; uidState: TOP ; uidBFSL: [BFSL]; intent: Intent { cmp=xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.scanner.ScannerService }; code:PROC_STATE_TOP; tempAllowListReason:<,reasonCode:SYSTEM_ALLOW_LISTED,duration:9223372036854775807,callingUid:-1>; targetSdkVersion:34; callerTargetSdkVersion:34; startForegroundCount:0; bindFromPackage:null: isBindService:false]; startForegroundDelayMs:18770
10-09 09:29:11.211 W/TelephonyPermissions( 2652): reportAccessDeniedToReadIdentifiers:xyz.malkki.neostumbler.fdroid:getActiveSubscriptionInfoList:5
10-09 09:29:11.219 E/AndroidRuntime(11201): Process: xyz.malkki.neostumbler.fdroid, PID: 11201
10-09 09:29:11.219 E/AndroidRuntime(11201): java.lang.SecurityException: Not allowed to bind to service Intent { cmp=xyz.malkki.neostumbler.fdroid/org.altbeacon.beacon.service.BeaconService }
10-09 09:29:11.221 W/ActivityTaskManager( 1497):   Force finishing activity xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity
10-09 09:29:11.227 I/ActivityManager( 1497): Showing crash dialog for package xyz.malkki.neostumbler.fdroid u0
10-09 09:29:11.238 W/PackageConfigPersister( 1497): App-specific configuration not found for packageName: xyz.malkki.neostumbler.fdroid and userId: 0
10-09 09:29:11.269 D/CoreBackPreview( 1497): Window{168c4a8 u0 Application Error: xyz.malkki.neostumbler.fdroid}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@111e8ec, mPriority=0, mIsAnimationCallback=false}
10-09 09:29:11.300 I/AppLocaleUtil(25350): Can display preference - [xyz.malkki.neostumbler.fdroid] : isDisallowedPackage : false / isSignedWithPlatformKey : false / hasLauncherEntry : true / canDisplay : true / 1.1
10-09 09:29:11.296 V/WindowManager( 1497):         {WCT{RemoteToken{d956adc Task{ba194fe #3025 type=standard A=10391:xyz.malkki.neostumbler.fdroid}}} m=CLOSE f=NONE leash=Surface(name=Task=3025)/@0xbdb39ae sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}
10-09 09:29:11.426 D/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(22862): Notification 6666 posted: packageName=xyz.malkki.neostumbler.fdroid, priority=-1, category=service
10-09 09:29:11.807 V/WindowManager( 1497): Loading animations: layout params pkg=xyz.malkki.neostumbler.fdroid resId=0x1030308
10-09 09:29:11.834 D/CoreBackPreview( 1497): Window{cfcf0d1 u0 xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity}: Setting back callback null
10-09 09:29:11.837 W/InputManager-JNI( 1497): Input channel object 'cfcf0d1 xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity (client)' was disposed without first being removed with the input manager!
10-09 09:29:12.048 W/ndroid.settings(25350): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/base.apk' with 1 weak references
10-09 09:29:12.640 D/CoreBackPreview( 1497): Window{168c4a8 u0 Application Error: xyz.malkki.neostumbler.fdroid}: Setting back callback null
10-09 09:29:12.640 I/ActivityManager( 1497): Killing 11201:xyz.malkki.neostumbler.fdroid/u0a391 (adj 50): crash
10-09 09:29:12.644 W/InputManager-JNI( 1497): Input channel object '168c4a8 Application Error: xyz.malkki.neostumbler.fdroid (client)' was disposed without first being removed with the input manager!
10-09 09:29:12.663 D/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(22862): Notification 6666 removed: packageName=xyz.malkki.neostumbler.fdroid, priority=-1, category=service
10-09 09:29:12.684 V/ActivityManager( 1497): Got obituary of 11201:xyz.malkki.neostumbler.fdroid
10-09 09:29:14.564 W/droid.launcher3(17543): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/base.apk' with 1 weak references
10-09 09:29:15.498 D/HotseatPredictionController(17543): } targetComponent=ComponentInfo{xyz.malkki.neostumbler.fdroid/xyz.malkki.neostumbler.MainActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=NeoStumbler), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd
10-09 09:29:39.369 W/system_server( 1497): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~paz7pd4ZuRljKTIQCBjK5A==/xyz.malkki.neostumbler.fdroid-XdRTVrLbStdXqB9JgJGUcg==/base.apk' with 1 weak references
```

### New bug

- [X] I have checked that this bug has not been reported before

**Comment by mjaakko** [comment]
This might be the same issue as #157. LineageOS has some custom settings for disabling "tracking services", which includes the beacon scanning service

**Comment by DocSniper** [comment]
I have now found the error and the solution and understand why everything was working until a few days ago.
I occasionally use [AppManager](https://muntashirakon.github.io/AppManager/en/) to block trackers, and I must have accidentally blocked NeoStumbler in the process.
Now, after unblocking all the trackers, NeoStumbler is working again.
It might be useful to mention somewhere in the ReadMe that the trackers are not malicious and are necessary for correct functionality, so they should not be blocked.
Anyway, sorry for the false alarm. 😉

![NeoStumbler2](https://github.com/user-attachments/assets/06e91289-3a0f-4bc7-9da7-d2606909c8f0)

**Comment by mjaakko** [comment]
I'll investigate if it would be possible to catch the error and show a warning if you have disabled the beacon service

**Comment by mjaakko** [comment]
I created a fix to catch the error found on the logs you posted. Unfortunately I don't have access to a LineageOS device so I can't test how it works in practice

**Comment by flame-0** [comment]
Just wanted to mention - it's not actually about LineageOS, a custom ROM, or what device you have. Instead, it's the open-source app called [App Manager](https://github.com/MuntashirAkon/AppManager) that blocks trackers, even the good ones. They have a feature that blocks all trackers at once.

**Comment by DocSniper** [comment]
Will test it as soon as a new version is released. 
Thanks. 😄

**Comment by DocSniper** [comment]
I tested the F-Droid release 1.4.0-rc1.
After blocking the trackers, the app starts, I see the logo splash screen, and then the app turns black and appears to be stuck.
The log is attached...
[20241104-NeoStumbler.log](https://github.com/user-attachments/files/17617353/20241104-NeoStumbler.log)

**Comment by flame-0** [comment]
> I tested the F-Droid release 1.4.0-rc1. After blocking the trackers, the app starts, I see the logo splash screen, and then the app turns black and appears to be stuck. The log is attached... [20241104-NeoStumbler.log](https://github.com/user-attachments/files/17617353/20241104-NeoStumbler.log)

I can reproduce the same issue on my end.

```
FATAL EXCEPTION: main
Process: xyz.malkki.neostumbler, PID: 871
java.lang.RuntimeException: Unable to create application xyz.malkki.neostumbler.StumblerApplication: java.lang.RuntimeException: Cannot get job id from manifest.  Make sure that the immediateScanJobId is configured in the manifest for the ScanJob.
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7403)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.app.ActivityThread.main(ActivityThread.java:8592)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.RuntimeException: Cannot get job id from manifest.  Make sure that the immediateScanJobId is configured in the manifest for the ScanJob.
 at org.altbeacon.beacon.service.ScanJob.getJobIdFromManifest(Unknown Source:78)
 at org.altbeacon.beacon.service.ScanJob.getImmediateScanJobId(Unknown Source:33)
 at org.altbeacon.beacon.service.ScanJobScheduler.cancelSchedule(Unknown Source:8)
 at org.altbeacon.beacon.BeaconManager.setEnableScheduledScanJobs(Unknown Source:55)
 at xyz.malkki.neostumbler.StumblerApplication.onCreate(Unknown Source:22)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1392)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7398)
 ... 9 more
```

https://github.com/user-attachments/assets/3f8bb92d-2aa4-46e4-a5c1-f48f3c462602

**Comment by mjaakko** [comment]
Thanks for the logs. This should be easy to fix
