### ISSUE TITLE
Geocoder error

### ISSUE THREAD

**Issue by Jose92** [mjaakko/NeoStumbler#77]
Hello,

Here's an error I'm seeing in my logcat on an Android terminal, version 11, without google services.

```
2024-05-19 10:21:48.837 15520-15520 GetAddressKt$getAddress xyz.malkki.neostumbler.fdroid.dev    W  Failed to geocode address for location XX.XXXXX, XX.XXXXX (Ask Gemini)
java.io.IOException: Missing INTERNET permission
at android.location.Geocoder.getFromLocation(Geocoder.java:136)
at xyz.malkki.neostumbler.extensions.GeocoderExtensionsKt$getFromLocationSuspending$3.invokeSuspend(geocoderExtensions.kt:32)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```                                                                  	
Maybe it would be interesting to be able to disable the geocoder.        

Thanks for your great work!

**Comment by mjaakko** [comment]
There is a check for not using the geocoder if it's not available: https://github.com/mjaakko/NeoStumbler/blob/3a42a6f58fe59231ef80ecac3a0a9940a869a1ec/app/src/main/java/xyz/malkki/neostumbler/extensions/geocoderExtensions.kt#L14

But that might not work if your OS has a mock implementation for the geocoder

I guess there could be a setting for disabling the geocoder altogether or it could be disabled dynamically if geocoding fails with IOException too many times - this would also be useful in case there is no Internet connection
