### ISSUE TITLE
Tile issue

### ISSUE THREAD

**Issue by Jose92** [mjaakko/NeoStumbler#92]
Hello, while using the quicksettings tile I noticed that it didn't seem to work, here is the error in the logs.

```
2024-06-01 09:15:36.653  4242-4293  AndroidRuntime          xyz.malkki.neostumbler.fdroid        E  FATAL EXCEPTION: DefaultDispatcher-worker-5 (Ask Gemini)
   Process: xyz.malkki.neostumbler.fdroid, PID: 4242
   java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{3012e3a 4242:xyz.malkki.neostumbler.fdroid/u0a396} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
   	at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
   	at android.os.Parcel.createException(Parcel.java:3226)
   	at android.os.Parcel.readException(Parcel.java:3209)
   	at android.os.Parcel.readException(Parcel.java:3151)
   	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7164)
   	at android.app.Service.startForeground(Service.java:776)
   	at t4.w.q(Unknown Source:365)
   	at a3.a.p(Unknown Source:7)
   	at s3.L.run(Unknown Source:114)
   	at z3.a.run(Unknown Source:95)
   	Suppressed: x3.g: [t0{Cancelling}@4db001e, Dispatchers.Default]
   Caused by: android.os.RemoteException: Remote stack trace:
   	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2882)
   	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2569)
   	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1835)
   	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14077)
   	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3578)
```

All permissions have been granted.

**Comment by mjaakko** [comment]
This seems to be caused by the lack of ACCESS_BACKGROUND_LOCATION permission: https://developer.android.com/develop/background-work/services/foreground-services#wiu-restrictions
